name: 'push/pull = make lint'
on: push

jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run:
        pip install poetry
        make install
    - name: Run linter
      run:
        make lint
  
